### ISSUE TITLE
Apache 2.4 apply but error occur !!

### ISSUE THREAD

**Issue by tklee1223** [greg-1-anderson/mod_auth_cookie#1]
I apply 'mod_auth_cookie' with  Apache HTTPServer version  2.2.31  ( four years old )
----------------------------------------------------
 # Windows Envirenment
1) copy to ~\Apache24\modules\mod_auth_cookie.so

2) ~\Apache24\conf\httpd.conf  add below
   LoadModule auth_cookie_module modules/mod_auth_cookie.so
-----------------------------------------------------

It is good! It's well 

we will update system.

I test 'mod_auth_cookie' with  Apache HTTPServer  version 2.4.43 ( also Apache HTTPServer  latest version 2.4.46  )

I fail to apply 'mod_auth_cookie'!!

----------------------------------------------------
command-line  > execute with : httpd -e debug

result > error log => Apache HTTPServer 2.4.43 version : 
httpd: Syntax error on line 186 of D:/httpd-2.4.43-win64-VS16/Apache24/conf/httpd.conf: 
Cannot load modules/mod_auth_cookie.so into server: %1\xc0\xba(\xb4\xc2) \xbf\xc3\xb9\xd9\xb8\xa5 Win32 \xc0\xc0\xbf\xeb \xc7\xc1\xb7\xce\xb1\xd7\xb7\xa5\xc0\xcc \xbe\xc6\xb4\xd5\xb4\xcf\xb4\xd9.

result > error log => Apache HTTPServer 2.4.46 version : 
httpd: Syntax error on line 186 of D:/httpd-2.4.46-win64-VS16/Apache24/conf/httpd.conf: 
Cannot load D:\\httpd-2.4.46-win64-VS16\\Apache24\\modules\\mod_auth_cookie.so into server: %1\xc0\xba(\xb4\xc2) \xbf\xc3\xb9\xd9\xb8\xa5 Win32 \xc0\xc0\xbf\xeb \xc7\xc1\xb7\xce\xb1\xd7\xb7\xa5\xc0\xcc \xbe\xc6\xb4\xd5\xb4\xcf\xb4\xd9.
-----------------------------------------------------

what's problem??

help me please !!

p/s
'mod_auth_cookie.so' file is attached by below!!

if compile problem, Anyone give me a  new compiled file 'mod_auth_cookie.so' ?
( email : lejworld@naver.com )

if apach bug problem, please comment about reference-link !

[mod_auth_cookie.zip](https://github.com/greg-1-anderson/mod_auth_cookie/files/5310238/mod_auth_cookie.zip)

**Comment by greg-1-anderson** [comment]
Wow, I completely forgot that I wrote this. Please consider this project abandoned; I will not be providing any future releases or support.
